### ISSUE TITLE
Display on multiple monitors

### ISSUE THREAD

**Issue by hcjl** [gitneeraj/lightdm-webkit2-theme-reactive#27]
Hey,
thanks a lot for the great work. This is really the most beautiful greeter, I have seen so far. So please keep up the great work!
I have just on short question/feature request ;-)

I would like to display the greeter on all attached monitors. I fiddled around with the `display-setup-script` in `/etc/lightdm/lightdm.conf` taken from the [arch wiki](https://wiki.archlinux.org/title/LightDM#LightDM_displaying_in_wrong_monitor). But it is always just showing on one of the monitors.

This does not prevent me from using it, but it would be a really nice-to-have for me.
Thanks & BR & Stay healthy!

**Comment by gitneeraj** [comment]
I have searched over the internet and found that its mostly likely an limitation in lightdm itself for the obvious reasons that it will create multiple sessions for multiple monitors in which login screen appears, which I feel is the conflict in interest of using a secure login such as with lightdm.

You could go through this reddit post https://www.reddit.com/r/linuxquestions/comments/m19gc7/lightdm_on_2_monitors/ which explains some methods and the issues with it.

Since this feature request is out of scope of the greeter and lightdm itself, I will have to close this out. But thanks for taking out time and mentioning this. Feel free to open new issue when you come across.

Cheers & Peace!
